nelmio_api_doc:
    documentation:
        info:
            title: Sample Records API
            description: Informacion de los endpoints de la API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
